name: SauceDemo Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest  # Changed to Windows runner
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      # Install Chrome (already included in windows-latest)
      - name: Install dependencies
        run: |
          npm install
          npm install -g chromedriver@latest
      
      # Run tests with Chrome
      - name: Run tests
        run: npm test
        env:
          BROWSER: chrome